[package]
name = "arguably"
version = "0.4.1"
authors = ["Darren Mulholland <dmulholl@tcd.ie>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/dmulholl/arguably"
description = "A simple argument-parsing library."

