[package]
name = "arguably"
version = "0.1.0"
authors = ["Darren Mulholland <dmulholl@tcd.ie>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/dmulholl/arguably"
description = "A ridiculously simple argument parsing library."

